# This is the final, simplified render.yaml that aligns with Render's latest native environment specs.
services:
  # 1. Your Spring Boot Web Service
  - type: web
    name: attendance-app
    # By removing the 'runtime' key, we let Render's build system
    # infer the environment from the build command.
    plan: free
    branch: main
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/attendance-app-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        fromDatabase:
          name: attendance-db-mishty # Must match the database name below
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: attendance-db-mishty # Must match the database name below
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: attendance-db-mishty # Must match the database name below
          property: password

  # 2. Your PostgreSQL Database
  - type: pserv
    name: attendance-db-mishty
    plan: free