# This file tells Render how to deploy your services.
services:
  # This is your main Spring Boot application
  - type: web
    name: attendance-app
    # THIS IS THE MOST IMPORTANT LINE: Force the environment to be Java
    env: java
    # Plan: "free" for the free tier
    plan: free
    # Build and start commands
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/attendance-app-0.0.1-SNAPSHOT.jar"
    # Link to your PostgreSQL database
    # Make sure the 'name' here matches the name you gave your database on Render
    # And the 'property' matches the environment variable name in your application.properties
    envVars:
      - key: DB_URL
        fromDatabase:
          name: attendance-postgres-db # <-- IMPORTANT: Change this if your DB has a different name
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: attendance-postgres-db # <-- IMPORTANT: Change this if your DB has a different name
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: attendance-postgres-db # <-- IMPORTANT: Change this if your DB has a different name
          property: password

  # This section defines your PostgreSQL database
  # Make sure the 'name' here matches the name you used above
  - type: pserv
    name: attendance-postgres-db # <-- IMPORTANT: Change this if your DB has a different name
    # The database engine
    ipAllowList: [] # Allows all connections, or you can restrict it
    plan: free
    # Use 'postgres' for PostgreSQL
    databaseName: attendance_db # This will be the name of the actual DB inside the server
    user: db_user # You can choose a username