services:
  - type: web
    name: attendance-app
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    branch: main
    repo: https://github.com/mishtydak/ssps
    envVars:
      - key: JAVA_VERSION
        value: 17
