# This version uses the CORRECT database name you found.
services:
  # 1. Your Spring Boot Web Service
  - type: web
    name: attendance-app
    # Use Docker to ensure a perfect environment
    env: docker
    plan: free
    healthCheckPath: /actuator/health
    # Environment variables that link to the CORRECT database below
    envVars:
      - key: DB_URL
        fromDatabase:
          # ******* THIS IS THE FIX *******
          name: attendance-app-db # This now matches the real name of your database
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          # ******* THIS IS THE FIX *******
          name: attendance-app-db # This now matches the real name of your database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          # ******* THIS IS THE FIX *******
          name: attendance-app-db # This now matches the real name of your database
          property: password
      - key: SERVER_PORT
        value: 8080

  # 2. Your PostgreSQL Database
  # The name here MUST also match the real name.
  - type: pserv
    name: attendance-app-db # ******* THIS IS THE FIX *******
    plan: free